### ISSUE TITLE
Latest Debian Bookworm on Raspberry Error 

### ISSUE THREAD

**Issue by psytron** [ideoforms/signalflow#109]
Attempting to follow the Linux install instructions:  from the docs: 
```
pip install signalflow
```
Result: 
```
ERROR: Could not find a version that satisfies the requirement
ERROR: No matching distribution found for signalflow
```
This is on Linux, Debian,  Raspberry Pi using latest Linux Debian Bookworm.

**Comment by ideoforms** [comment]
Hmm, there should be some Raspberry Pi builds in PyPi, at least for Python 3.8 to 3.11.
What generation of Raspberry Pi was this running on, and what version of Python?
Would you also be able to run `python -m pip debug --verbose` and paste the output from below `Compatible tags`?
That will help me pin down why pip isn't matching anything.
(It may be quite long...)

**Comment by ideoforms** [comment]
Debian Bookworm builds are now available for x86_64 and arm64 (Raspberry Pi), verified here.
