### ISSUE TITLE
Documentation: Add "build from source" section

### ISSUE THREAD

**Issue by shakfu** [ideoforms/signalflow#114]
May I suggest that the docs make explicit the prerequisites to build `signal flow` such as `soundio` and `libsndfile`, which in my case on macOS required `brew install libsoundio libsndfile`.

The current documents don't mention these (at least I coundn't find any mention), and these are only apparent  If one tries to build via `python3 setup.py build`, or by looking into the `CMakeLists.txt` file. 

After installing the above two libs, I was able to build `signalflow` via `python3 setup.py build`, but there was a warning about not finding `vamp`:

```text
CMake Warning at CMakeLists.txt:201 (message):
  Couldn't find vamp
```
Is this optional? How does one install `vamp` for example?

**Comment by ideoforms** [comment]
Thanks @shakfu. This is documented in "Building from source" in [CONTRIBUTING.md](https://github.com/ideoforms/signalflow/blob/master/CONTRIBUTING.md), but I appreciate that this isn't very well signposted... I'll add an explicit section in the online docs for this.

vamp is an optional dependency, hence being a warning not a fatal. If you install [vamp-plugins](https://www.vamp-plugins.org/) (which can be done using homebrew on macOS), it should detect and compile with vamp support automatically. Be warned that vamp support is not yet very mature or documented.

**Comment by shakfu** [comment]
Thanks!
