### ISSUE TITLE
How to turn a Node on (.play()) without playing it

### ISSUE THREAD

**Issue by jarmitage** [ideoforms/signalflow#119]
```py
audio_path = '...'
audio_buf = Buffer(audio_path)
player = BufferPlayer(audio_buf)
player.play() # this will also .trigger() the sample

player.trigger() # cant do this without doing .play() first
```

**Comment by ideoforms** [comment]
Thanks @jarmitage - just working through the backlog of outstanding issues...!
You can achieve this by setting the `clock` input to `0`; have now added this to the [documentation](https://signalflow.dev/library/buffer/bufferplayer/).
