### ISSUE TITLE
cmake error on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by danstowell** [ideoforms/signalflow#85]
Maybe Ubuntu 18.04 LTS is too old for you - if so, no problem (but please document that?).  Else, read on...

Here's my system:

```
 % lsb_release -a
Description:	Ubuntu 18.04.5 LTS
 % cmake --version
cmake version 3.10.2
```

And here's the cmake error:

```
 % python setup.py build

Found libsoundio
Found sndfile
Found fftw3f
CMake Warning at CMakeLists.txt:151 (message):
  Couldn't find vamp

-- Configuring done
-- Generating done
-- Build files have been written to: /home/dans/dev/github/signalflow/build/temp.linux-x86_64-3.6
Unknown argument -j
Unknown argument 8
Usage: cmake --build <dir> [options] [-- [native-options]]

...

subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '-j', '8']' returned non-zero exit status 1.
```

The first cmake that supports `-j` is 3.12. I tend to try and stick with the standard apt repositories, so if it's easy to handle this then simple-minded users like me ;) would be able to get in...

**Comment by danstowell** [comment]
If I delete the `-j` to get past there, then I hit one thing I'll file a separate issue about, plus one that's related to this: `FindPython3` is not found, because it was [new in cmake version 3.12](https://cmake.org/cmake/help/latest/module/FindPython3.html). Maybe my cmake is indeed too old - it could take a lot of patching to support it.

**Comment by ideoforms** [comment]
Argh, that's a shame. I have gone through a few different permutations of cmake FindPython/FindPython3, and this specific configuration resolved some issues with the previous version.

I think you're right, requiring cmake 3.12 is probably the least impactful approach to mitigate this - just pushed that as a "fix" for now.

**Comment by ideoforms** [comment]
I've updated the README stipulating 20.04 as a requirement. Cheers!
